### ISSUE TITLE
Can't assign class to table

### ISSUE THREAD

**Issue by alexstorer** [dbohdan/csv2html#4]
I'm trying to output a table that needs some CSS.  Unfortunately, the `html` module isn't designed to allow this:

`self.table = self.html.table(border='1')`

It should work like this, but this is a syntax error in Python because class is protected syntax.

`self.table = self.html.table(border='1', class='table')`

**Comment by dbohdan** [comment]
Look in the README for the module `html` at https://pypi.python.org/pypi/:

>Since we can't use class as a keyword, the library recognises klass as a substitute:
>`>>> print h.p(content, klass="styled")`
>`<p class="styled">content</p>`

**Comment by alexstorer** [comment]
Oh, snap. :+1:
