### ISSUE TITLE
Add support for Adding border to generated Table.

### ISSUE THREAD

**Issue by ket000** [dbohdan/csv2html#7]
Currently the table generated does not add support for displaying the border. I am using this program to send an html email and without border it looks ugly. I was able to modify the generated html output by adding the below style statement. 

<style>table,th,td {padding: 10px;border: 1px solid black;border-collapse: collapse;}

and using the below to add it at the top and send HTML email. 

cat test.html  | xargs -0  printf "Content-Type: text/html\nSubject: Test\n%s"
xargs -0  printf "Content-Type: text/html\nSubject: Test email \n<style>table,th,td {padding: 10px;border: 1px solid black;border-collapse: collapse;}\n%s" | sendmail aaa@aaa.com

**Comment by pschonmann** [comment]
Im using --table border=1 and im happy with it

**Comment by dbohdan** [comment]
You can also use the `--table` argument with the [`style` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/style).
