### ISSUE TITLE
Any chance you will officially have mac binaries

### ISSUE THREAD

**Issue by anantshri** [dbohdan/csv2html#9]
I have tried compiling mac binaries on mac using `cargo build --release` resultant binary is working flawlessly for my limited use case.

Just wanted to check if there is any plan to release mac binaries officially.

**Comment by dbohdan** [comment]
Sorry, not at the moment. I don't currently use macOS, and I'd rather not publish binaries I can't test. I'll add a Mac binary if this changes.
